data-wrangling/data_wrangling/__init__.py
__version__ = '0.1.1'

data-wrangling/data_wrangling/blueprints/main/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

main = Blueprint('main', __name__, template_folder="templates/main")


@main.route("/")
def index():
    return render_template('index.html')

@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('layouts/404.html'), 404

data-wrangling/data_wrangling/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  data rodeo
</h1>
<h2 class="subtitle">
  a place to wrangle data
</h2>
{% endblock %}

data-wrangling/data_wrangling/templates/layouts/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>data rodeo home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                sign up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

data-wrangling/data_wrangling/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">login here</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="your email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="your password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">login</button>
        </form>
    </div>
</div>
{% endblock %}

data-wrangling/data_wrangling/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  welcome!
</h1>
{% endblock %}

data-wrangling/data_wrangling/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">sign up here</h3>
    <div class="box">
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">sign up</button>
        </form>
    </div>
</div>
{% endblock %}